---
deployment:
  tasks:
    - export DEPLOYPATH=/home/colomboh/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R admin $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R controllers $DEPLOYPATH
    - /bin/cp -R DB $DEPLOYPATH