
<?php
include '../DB/DB.php';
global $connection;

//$member_id = $_COOKIE['member_id'];
$member_tag = $_GET['tag'];
$member_id = explode("#", $member_tag)[0];

$sql_loadProvince = "SELECT * FROM provinces";

$sql_loadMemberDetails = "SELECT * FROM members WHERE id='$member_id'";
$result_memberDetails = mysqli_query($connection, $sql_loadMemberDetails);
$row_memberDetails = mysqli_fetch_assoc($result_memberDetails);

//include './header.php';
//include './menu.php';
?>

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta content="width=device-width, initial-scale=1.0" name="viewport">

        <title>LCCH - <?php echo $row_memberDetails['first_name'] . $row_memberDetails['last_name']; ?></title>
        <meta content="" name="description">
        <meta content="" name="keywords">

        <!-- Favicons -->
        <link href="../assets/img/leo-logo-favicon2.png" rel="icon">
        <link href="../assets/img/leo-logo-favicon2.png" rel="apple-touch-icon">

        <!-- Google Fonts -->
        <link href="https://fonts.gstatic.com" rel="preconnect">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

        <!-- Vendor CSS Files -->
        <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
        <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
        <link href="assets/vendor/quill/quill.snow.css" rel="stylesheet">
        <link href="assets/vendor/quill/quill.bubble.css" rel="stylesheet">
        <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
        <link href="assets/vendor/simple-datatables/style.css" rel="stylesheet">

        <!-- Template Main CSS File -->
        <link href="assets/css/style.css" rel="stylesheet">

        <style>
            .myLeo {
                background-image: url('assets/img/icons/MyLeo-icon.jpeg');
                background-repeat: no-repeat;
                display: inline-block;
                width: 32px;
                height: 32px
            }
            .lcch {
                background-image: url('assets/img/icons/Lcch-icon.jpeg');
                background-repeat: no-repeat;
                display: inline-block;
                width: 32px;
                height: 32px
            }
            .myLci {
                background-image: url('assets/img/icons/MyLCI-icon.jpeg');
                background-repeat: no-repeat;
                display: inline-block;
                width: 32px;
                height: 32px
            }


            .slide-top {
                -webkit-animation: slide-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
                animation: slide-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
            }

            /* ----------------------------------------------
 * Generated by Animista on 2022-7-12 22:42:2
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

            /**
             * ----------------------------------------
             * animation slide-top
             * ----------------------------------------
             */
            @-webkit-keyframes slide-top {
                0% {
                    -webkit-transform: translateY(0);
                    transform: translateY(0);
                }
                100% {
                    -webkit-transform: translateY(-20px);
                    transform: translateY(-20px);
                }
            }
            @keyframes slide-top {
                0% {
                    -webkit-transform: translateY(0);
                    transform: translateY(0);
                }
                100% {
                    -webkit-transform: translateY(-20px);
                    transform: translateY(-20px);
                }
            }

        </style>

    </head>

    <body>


        <div class="container-fluid">

            <div class="row">

                <div class="col-lg-12">

                    <div class="card">
                        <div class="card-body">
                            <br>

                            <div class="col-md-12">
                                <img src="assets/img/myProfile-background.jpeg" class="img-fluid" style="border-radius: 30px">
                                <img src="assets/img/profile_imgs/<?php echo $row_memberDetails['image']; ?>" class="rounded-circle float-left" style="width: 200px; border-style: solid; border-width: 10px; border-color: white; margin-top: -90px; margin-left: 50px">                          
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <br>
                                </div>
                                <div class="col-md-2"></div>
                                <div class="col-md-8">
                                    <center>
                                        <button type="button" id="about-btn" class="btn btn-outline-secondary" onclick="viewBlock('#about')">About</button>
                                        <button type="button" id="education-btn" class="btn btn-outline-secondary" onclick="viewBlock('#education')">Education</button>
                                        <button type="button" id="profession-btn" class="btn btn-outline-secondary" onclick="viewBlock('#profession')">Employment</button>
                                        <button type="button" id="social-btn" class="btn btn-outline-secondary" onclick="viewBlock('#social')">Social Media</button>

                                    </center>
                                </div>
                                <div class="col-md-2"></div>

                            </div>
                        </div>

                    </div>
                </div>

            </div>
            <form>
                <!--About Card-->
                <div class="col-lg-12 slide-top" style="display: none" id="about">

                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">About</h4>

                            <div class="row">

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name" value="<?php echo $row_memberDetails['first_name']; ?>" disabled>
                                        <label for="floatingName">First Name</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="middle_name" name="middle_name" placeholder="Middle Name" value="<?php echo $row_memberDetails['middle_name']; ?>" disabled>
                                        <label for="floatingName">Middle Name</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="last_name" name="last_name" value="<?php echo $row_memberDetails['last_name']; ?>" placeholder="Last Name" disabled>
                                        <label for="floatingName">Last Name</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="most_used_name" name="most_used_name" placeholder="Most Used Name" value="<?php echo $row_memberDetails['most_used_name']; ?>" disabled>
                                        <label for="floatingName">Most Used Name</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="email" class="form-control" id="email" name="email" placeholder="Email Address" value="<?php echo $row_memberDetails['email']; ?>" disabled>
                                        <label for="floatingName">Email Address</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="date" class="form-control" id="dob" name="dob" placeholder="Date of Birth" value="<?php echo $row_memberDetails['dob']; ?>" disabled>
                                        <label for="floatingName">Date of Birth</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">

                                        <input type="text" class="form-control" id="address_line1" name="address_line1" placeholder="Address Line 1" value="<?php echo $row_memberDetails['address_line1']; ?>" disabled>

                                        <label for="floatingName">Address Line 1</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">

                                        <input type="text" class="form-control" id="address_line2" name="address_line2" placeholder="Address Line 2" value="<?php echo $row_memberDetails['address_line2']; ?>" disabled>

                                        <label for="floatingName">Address Line 2</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">

                                        <input type="text" class="form-control" id="address_line3" name="address_line3" placeholder="Address Line 3" value="<?php echo $row_memberDetails['address_line3']; ?>" disabled>

                                        <label for="floatingName">Address Line 3</label>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="Province" name="Province" placeholder="Province" value="<?php echo $row_memberDetails['province']; ?>" disabled>
                                        <label for="floatingName">Province</label>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="District" name="District" placeholder="District" value="<?php echo $row_memberDetails['district']; ?>" disabled>
                                        <label for="floatingName">District</label>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="city" name="city" placeholder="city" value="<?php echo $row_memberDetails['city']; ?>" disabled>
                                        <label for="floatingName">City</label>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Postal Code" value="<?php echo $row_memberDetails['postal_code']; ?>" disabled>
                                        <label for="floatingName">Postal Code</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="Gender" name="Gender" placeholder="Postal Code" value="<?php echo $row_memberDetails['postal_code']; ?>" disabled>
                                        <label for="floatingName">Gender</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Postal Code" value="<?php echo $row_memberDetails['postal_code']; ?>" disabled>
                                        <label for="floatingName">Preferred Language</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Postal Code" value="<?php echo $row_memberDetails['postal_code']; ?>" disabled>
                                        <label for="floatingName">MyLCI Number</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Telephone - Residence" disabled>
                                        <label for="floatingName">Telephone - Residence</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Mobile" disabled>
                                        <label for="floatingName">Mobile</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Secondary Mobile" disabled>
                                        <label for="floatingName">Secondary Mobile</label>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Secondary Mobile" disabled>
                                        <label for="floatingName">National Identity Card Number</label>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Secondary Mobile" disabled>
                                        <label for="floatingName">Civil Status</label>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>

                <!--Education Card-->
                <div class="col-lg-12 slide-top" style="display: none" id="education">

                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Education</h4>

                            <div class="row">

                                <div class="col-md-6">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="School Name" disabled>
                                        <label for="floatingName">School Name</label>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Start Date" disabled>
                                        <label for="floatingName">Start Date</label>
                                    </div>
                                </div>

                                <div class="col-md-3">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="End Date" disabled>
                                        <label for="floatingName">End Date</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="University Name" disabled>
                                        <label for="floatingName">University Name</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="University Name" disabled>
                                        <label for="floatingName">Level of Education</label>
                                    </div>
                                </div>


                                <div class="col-md-2">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Start Date" disabled>
                                        <label for="floatingName">Start Date</label>
                                    </div>
                                </div>

                                <div class="col-md-2">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="End Date" disabled>
                                        <label for="floatingName">End Date</label>
                                    </div>
                                </div>



                            </div>

                        </div>
                    </div>

                </div>

                <!--Profession Card-->
                <div class="col-lg-12 slide-top" style="display: none" id="profession">

                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Employment</h4>

                            <div class="row">

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="School Name" value="<?php echo $row_memberDetails['working_place']; ?>" disabled>
                                        <label for="floatingName">Company Name</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Start Date" value="<?php echo $row_memberDetails['designation']; ?>" disabled>
                                        <label for="floatingName">Profession</label>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <div class="form-floating mb-3">
                                        <input type="text" class="form-control" id="twitter" name="twitter" placeholder="Start Date" value="<?php echo $row_memberDetails['profession_category']; ?>" disabled>
                                        <label for="floatingName">Category of Profession</label>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>

                <!--Social Media Card-->
                <div class="col-lg-12 slide-top" style="display: none" id="social">

                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Social Media</h4>

                            <div class="row">

                                <div class="col-md-6">
                                    <div class="d-grid gap-2 mt-3">
                                        <a type="button" class="btn btn-secondary"><i class="bi bi-facebook me-1"></i> Facebook</a>
                                    </div>
                                </div>


                                <div class="col-md-6">
                                    <div class="d-grid gap-2 mt-3">
                                        <a type="button" class="btn btn-danger"><i class="bi bi-instagram me-1"></i> Instagram</a>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="d-grid gap-2 mt-3">
                                        <a type="button" class="btn btn-info"><i class="bi bi-twitter me-1"></i> Twitter</a>
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="d-grid gap-2 mt-3">
                                        <a type="button" class="btn btn-primary"><i class="bi bi-linkedin me-1"></i> LinkedIn</a>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="d-grid gap-2 mt-3">
                                        <a type="button" class="btn btn-dark"><i class="bi bi-tiktok me-1"></i> TikTok</a>
                                    </div>
                                </div>                           

                            </div>

                        </div>
                    </div>

                </div>
            </form>
        </div>

        <!-- ======= Footer ======= -->
        <footer  class="footer">
            <div class="copyright">
                &copy; Copyright <strong><span>LCCH</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                Designed by <a href="https://www.facebook.com/dineth.jayasekera.5">Dineth Jayasekera</a>
            </div>
        </footer><!-- End Footer -->

        <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

        <!-- Vendor JS Files -->
        <script src="assets/vendor/apexcharts/apexcharts.min.js"></script>
        <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="assets/vendor/chart.js/chart.min.js"></script>
        <script src="assets/vendor/echarts/echarts.min.js"></script>
        <script src="assets/vendor/quill/quill.min.js"></script>
        <script src="assets/vendor/simple-datatables/simple-datatables.js"></script>
        <script src="assets/vendor/tinymce/tinymce.min.js"></script>
        <script src="assets/vendor/php-email-form/validate.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

        <!-- Template Main JS File -->
        <script src="assets/js/main.js"></script>

        <script>
                                            /**
                                             * Set Active Menu
                                             */

                                            function setActiveMenu(colupsId = null, menuId = null, mainMenuId = null) {

                                                /**
                                                 * Remove Show From Colups
                                                 */

                                                $("#members-nav").removeClass("show");
                                                $("#config-nav").removeClass("show");
                                                $("#projects-nav").removeClass("show");

                                                /**
                                                 * Remove active From Menu
                                                 */

                                                $("#view_members").removeClass("active");
                                                $("#dashboard").removeClass("active");
                                                $("#president_message").removeClass("active");
                                                $("#ipp_message").removeClass("active");
                                                $("#ipp_message").removeClass("active");
                                                $("#config_general").removeClass("active");
                                                $("#add_projects").removeClass("active");
                                                $("#manage_projects").removeClass("active");
                                                $("#manage_accounts").removeClass("active");
                                                $("#participation").removeClass("active");

                                                /**
                                                 * Add active to main Menu
                                                 */

                                                $("#members-nav-main").addClass("collapsed");
                                                $("#projects-nav-main").addClass("collapsed");
                                                $("#config-nav-main").addClass("collapsed");
                                                $("#dashboard").addClass("collapsed");

                                                if (colupsId != null) {
                                                    $(colupsId).addClass("show");
                                                }
                                                if (menuId != null) {
                                                    $(menuId).addClass("active");
                                                }
                                                if (mainMenuId != null) {
                                                    $(mainMenuId).removeClass("collapsed");
                                            }
                                            }
        </script>

    </body>

</html>

<script>
    $('.toggle-sidebar-btn').trigger('click');
    /**
     * Exco Asign form submit
     */

    function viewBlock(id) {
        $("#about").css("display", "none");
        $("#education").css("display", "none");
        $("#profession").css("display", "none");
        $("#social").css("display", "none");


        $("#about-btn").removeClass("btn-danger");
        $("#education-btn").removeClass("btn-danger");
        $("#profession-btn").removeClass("btn-danger");
        $("#social-btn").removeClass("btn-danger");


        $("#about-btn").addClass("btn-outline-secondary");
        $("#education-btn").addClass("btn-outline-secondary");
        $("#profession-btn").addClass("btn-outline-secondary");
        $("#social-btn").addClass("btn-outline-secondary");


        $(id + "-btn").removeClass("btn-outline-secondary");
        $(id + "-btn").addClass("btn-danger");

        $(id).css("display", "block");
    }


    viewBlock('#about');
</script>